### ISSUE TITLE
undefined method `error' for true:TrueClass on 0.9.2

### ISSUE THREAD

**Issue by b3ccio** [hgmnz/truncate_html#36]
When I upgraded the gem to 0.9.1 or 0.9.2 it threw an exception I had to go back to 0.5.5.
